### ISSUE TITLE
Infinite requests by Partytown

### ISSUE THREAD

**Issue by RigottiG** [BuilderIO/partytown#170]
I'm facing an issue, I'm using `Partytown` but `Partyproxy` is making a lot of requests on each page I visit.

I'm using Next so I don't have any configs for `PartyTown` , just put my script's strategy as `worker`

![image](https://user-images.githubusercontent.com/13246770/166475480-31706f85-87e8-456d-8af8-0fd61c04494a.png)

**Comment by steve8708** [comment]
hey @RigottiG - we've just created an issue template, could you update your issue here to provide all the information the template asks for? it'll help us look into your issue https://github.com/BuilderIO/partytown/issues/new?assignees=&labels=&template=bug_report.md&title=

pasting below to make things easier:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Reproduction link**
Please include a link to a Stackblitz or Codesandbox reproducing the issue. We will need to see the issue reproduced with hand-written code - we can't debug giant minified third party scripts directly. If you do not include a clean and simple reproduction of your issue, we won't be able to look into it until you do.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by SatadruBhattacharjee** [comment]
+1 - Facing the same

**Comment by sylvain-a** [comment]
You are probably using partytown with the web worker (not atomics). In that case, I think the logs you are seeing are just the communication between the web worker and the main thread, through the service worker. As it uses XMLHttpRequest, they are logged by your network tab.

**Comment by Oumeir-Rengony-Hangar** [comment]
Facing same issue here

**Comment by ChanelZM** [comment]
+1

**Comment by jackeverydayzero** [comment]
You will see the answer here - https://partytown.builder.io/trade-offs.
I had the same problem.

**Comment by Anthony-eng21** [comment]
You need to enable the Atomics commumication layer to not see the internal xhr requests (these come from the default service worker and main thread sending data to each other) and, they claim that the way Atomics communicates to the main thread is 10X faster. How TODO: In your server environment you need to add some directives to modify your headers the docs talks about it [here](https://partytown.builder.io/atomics)

**Comment by PranuPranav97** [comment]
I am also having the same issue. After reading the [](https://partytown.builder.io/trade-offs)  I just cached the partytown scripts in my nextjs app by modifying next.config.js.

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  async headers() {
    return [
      {
        source: "/~partytown/:path*", // Match all files under the public/~partytown path
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=31536000, immutable", // Cache for 1 year (31536000 seconds)
          },
        ],
      },
    ];
  },
};

module.exports = nextConfig;

```
