### ISSUE TITLE
Service Worker not registering

### ISSUE THREAD

**Issue by Priyanshu-C** [BuilderIO/partytown#171]
I am trying to try a POC around Partytown, but i am not able to get it working. Getting the following error.
I am currently using react-helmet to initialize  Partytown.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/63398163/166889068-855821ad-85df-4875-9049-28f9f3f36529.png">

Have the following webpack config -> 
` {
            from: partytown.libDirPath(),
            to: path.join(__dirname, 'public', 'dist', '~partytown'),
          },`

**Comment by AdrianBlancoGarcia** [comment]
Have you solved it? I have the same problem

**Comment by steve8708** [comment]
hey @Priyanshu-C  - we've just created an issue template, could you update your issue here to provide all the information the template asks for? it'll help us look into your issue https://github.com/BuilderIO/partytown/issues/new?assignees=&labels=&template=bug_report.md&title=

pasting below to make things easier:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Reproduction link**
Please include a link to a Stackblitz or Codesandbox reproducing the issue. We will need to see the issue reproduced with hand-written code - we can't debug giant minified third party scripts directly. If you do not include a clean and simple reproduction of your issue, we won't be able to look into it until you do.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. To help us debug this further, would you be able to provide a way to replicate this? Creating a PR, with the minimal amount of code to re-create the issue would help us debug. 

Some more information can be found here: https://github.com/BuilderIO/partytown/blob/main/DEVELOPER.md#submitting-issues-and-writing-tests

Thank you for your help!

**Comment by linuxd3v** [comment]
you are maybe forgetting the https. Site has to be on https for Service Worker to work (or localhost).

**Comment by dannyk08** [comment]
Hello

I'm having the same issue but with this error 

```
DOMException: Failed to register a ServiceWorker for scope ('https://localhost:3000/~partytown/debug/') with script ('https://localhost:3000/~partytown/debug/partytown-sw.js'): An unknown error occurred when fetching the script.
window.console.error @ app-index.js:31
Promise.then (async)
u @ (index):2
```


### Context

1. I'm using NextJS ^13.4.12 so I can't use the [worker strategy](https://partytown.builder.io/nextjs#worker-strategy) because [NextJS Script](https://nextjs.org/docs/pages/api-reference/components/script#worker) v13 does not support it. 
2. This leads me to [copy all the scripts](https://partytown.builder.io/nextjs#copy-library-files) for partytown as the fallback approach.
3. I understand web workers won't work(👀) when using `http` 
   1. So, I `next start` the next preview server on port `3001`
   2. Then I use self certs and use another terminal to start the `local-ssl-proxy` to preview the build on port `3000` with `https`
   3. This is not the prettiest thing I know, but it has solved a lot of `https` issues with other services
4. Then I load `https://localhost:3000` and I see the web worker error on the console


### Extra Context

I've tried to load the `Partytown` helper in `client only` mode but that also hasn't worked.

```.tsx
// app/layout.tsx
import dynamic from 'next/dynamic'
import Tracking from 'component/Tracking'

const PartyTown = dynamic(
  async () => {
    return (await import('@builder.io/partytown/react')).PartyTown
  },
  { ssr: false },
)

const Home = () => {
  return (
    <>
      <head>
        <title>My App</title>
        <Partytown debug={true} forward={['dataLayer.push']} />
        <Tracking />
      </head>
      <body>
        <main>...</main>
      </body>
    </>
  );
};

export default Home;
```

I also want to point out that I'm clumping all my tracking scripts in another component, which should be fine.

```.tsx
// component/Tracking.tsx

import Script from 'next/script'

export default function Tracking() {
  return <>
    <Script
        strategy="lazyOnload"
        type="text/partytown"
        async
        src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXX"
      ></Script>
    
    <Script
        id="gtm-script"
        strategy="lazyOnload"
        type="text/partytown"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag() {dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-XXXXXXX');
          `,
        }}
      />
  </>
}
```

Hope this is enough detail to offer enough debugging. 

Let me know if you'd like me to provide more information.

Thank you 🙏🏽

**Comment by welfoz** [comment]
> Hello
> 
> I'm having the same issue but with this error
> 
> ```
> DOMException: Failed to register a ServiceWorker for scope ('https://localhost:3000/~partytown/debug/') with script ('https://localhost:3000/~partytown/debug/partytown-sw.js'): An unknown error occurred when fetching the script.
> window.console.error @ app-index.js:31
> Promise.then (async)
> u @ (index):2
> ```
> 
> ### Context
> 1. I'm using NextJS ^13.4.12 so I can't use the [worker strategy](https://partytown.builder.io/nextjs#worker-strategy) because [NextJS Script](https://nextjs.org/docs/pages/api-reference/components/script#worker) v13 does not support it.
> 2. This leads me to [copy all the scripts](https://partytown.builder.io/nextjs#copy-library-files) for partytown as the fallback approach.
> 3. I understand web workers won't work(👀) when using `http`
>    
>    1. So, I `next start` the next preview server on port `3001`
>    2. Then I use self certs and use another terminal to start the `local-ssl-proxy` to preview the build on port `3000` with `https`
>    3. This is not the prettiest thing I know, but it has solved a lot of `https` issues with other services
> 4. Then I load `https://localhost:3000` and I see the web worker error on the console
> 
> ### Extra Context
> I've tried to load the `Partytown` helper in `client only` mode but that also hasn't worked.
> 
> // app/layout.tsx
> import dynamic from 'next/dynamic'
> import Tracking from 'component/Tracking'
> 
> const PartyTown = dynamic(
>   async () => {
>     return (await import('@builder.io/partytown/react')).PartyTown
>   },
>   { ssr: false },
> )
> 
> const Home = () => {
>   return (
>     <>
>       <head>
>         <title>My App</title>
>         <Partytown debug={true} forward={['dataLayer.push']} />
>         <Tracking />
>       </head>
>       <body>
>         <main>...</main>
>       </body>
>     </>
>   );
> };
> 
> export default Home;
> I also want to point out that I'm clumping all my tracking scripts in another component, which should be fine.
> 
> // component/Tracking.tsx
> 
> import Script from 'next/script'
> 
> export default function Tracking() {
>   return <>
>     <Script
>         strategy="lazyOnload"
>         type="text/partytown"
>         async
>         src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXX"
>       ></Script>
>     
>     <Script
>         id="gtm-script"
>         strategy="lazyOnload"
>         type="text/partytown"
>         dangerouslySetInnerHTML={{
>           __html: `
>             window.dataLayer = window.dataLayer || [];
>             function gtag() {dataLayer.push(arguments);}
>             gtag('js', new Date());
>             gtag('config', 'G-XXXXXXX');
>           `,
>         }}
>       />
>   </>
> }
> Hope this is enough detail to offer enough debugging.
> 
> Let me know if you'd like me to provide more information.
> 
> Thank you 🙏🏽

Hi Danny! 
Did you finally find a way to make it work?
