### ISSUE TITLE
Error finding instance and failed analytics report bug

### ISSUE THREAD

**Issue by Avisaac** [BuilderIO/partytown#202]
We have an app that is server side rendered (Node express and Handlebars) and has Google tag manager and Google analytics reports in it.
We are trying to add partytown to improve our Lighthouse score and performance. 
We have a reverse proxy via Nginx. 

We are having two problems right now 
1. Sometimes the Partytown errors out with something unknown I don't understand why and when this happens but when it does it means the whole service worker does not really work at all. I think maybe this is some race condition because I sometimes get it sometimes I don't?
Screenshot
![image](https://user-images.githubusercontent.com/5303698/175068005-54eaba11-ab1a-4fe0-bcdc-2532096b8b90.png)

2. when partytown does load but the collect is a bit weird
We have one that is failing and the other two are marked as not completed and also one of them has all the dataLayer variables as undefined
Screenshots
![image](https://user-images.githubusercontent.com/5303698/175068293-78625386-e1c8-4665-bfca-207e9d7d0796.png)
![image](https://user-images.githubusercontent.com/5303698/175068506-ab245abe-c487-4aa5-981f-e67f99af5be9.png)

Version
"builder.io/partytown": "^0.6.0"

**Comment by mhevery** [comment]
We need a way to reproduce the issue otherwise there is not much we can do. Please provide a simple reproduction.

**Comment by royduin** [comment]
Related: https://github.com/BuilderIO/partytown/issues/72, having the same issue btw

**Comment by Avisaac** [comment]
Thanks @royduin I will look at that issue and see if any insight on a solution pops up
@mhevery , we have put that task of integrating partytwon aside for a few sprints and now are back to it, sorry for not being responsive on that. 
Im not sure what else data you need for reproducing, I am not sure what the cause for this error is so I was not able to actually setup any working reproduction of this error, if there any missing data on the stack/setup that we have that can help is missing please let me know and  I will supply

**Comment by mhevery** [comment]
As much as we would like to help, we need reproduction steps to dig into what is going on, screenshots are not enough. Without seeing the error on our machines, there is not much we can do.

**Comment by royduin** [comment]
As for #72; just install GTM and try to debug with https://tagassistant.google.com

**Comment by SujayPrabhu96** [comment]
Hi folks, even I am facing the same issue in preview mode. 
Error message is `Error finding instance "1wxccpy1m7t.d" on window 2 `

Here is the site for reproducing the issue: https://github.com/SujayPrabhu96/integrate-gatsby-google-tagmanager-using-partytown

Env needs to be set is:
`GATSBY_GOOGLE_TAG_MANAGER_TRACKING_ID`

**Comment by SujayPrabhu96** [comment]
@mhevery Is there any update on this issue ?

**Comment by szafran89** [comment]
I have the same issue with Nuxt3. Is there any solution?

**Comment by TheDutchCoder** [comment]
For us this happens when switching between tabs (some of our internal links open a new tab), I wonder if the Service Worker doesn't correctly deal with multiple tabs nd tracking which window belongs where?

**Comment by mhevery** [comment]
Can I ask for a  PR with tests showing the failure to simplify our reproduction of the issue. https://github.com/BuilderIO/partytown/blob/main/tests/integrations/gtm/index.html

**Comment by techfg** [comment]
> Can I ask for a PR with tests showing the failure to simplify our reproduction of the issue. https://github.com/BuilderIO/partytown/blob/main/tests/integrations/gtm/index.html

I believe there might be multiple issues going on here.  

The GTM Preview issues are well described by @slawekkolodziej in #72 along with [his solution and contribution](https://github.com/BuilderIO/partytown/issues/72#issuecomment-1596222803) - thank you @slawekkolodziej!

Underlying though, the `$instanceId$ not found` errors (`Error finding instance "2dab62yogpr.d" on window 2` in debug build) appear to be an issue when multiple tabs/pages are open and service workers are involved (problems do not seem to occur when atomics are used).  I created #492 since I'm easily able to reproduce the issue without GTM.

@mhevery - #493 contains a PR with tests and #492 describes how to manually reproduce as well - thank you!

**Comment by bsivaganeshan-eb** [comment]
Hi @sthobis,  Have you resolved the issue? I am also facing the same issue 

 data-pterror="Error: 25p416vnd9f.d not found
    at $e (blob:https://{host}/7aed8ded-2e59-4659-8c85-59aefdd3be9c:2:5065)

**Comment by jjpaulino** [comment]
I'm also facing this issue when switching tabs. Is there any update or has anyone found a workaround?

**Comment by MichelAraujo** [comment]
I'm also facing this issue when switching tabs. @jjpaulino found something?

**Comment by vladetsky** [comment]
@MichelAraujo @jjpaulino @mhevery I've added the fix [here](https://github.com/BuilderIO/partytown/pull/573)

**Comment by techfg** [comment]
@vladetsky - 

This is great, thank you!  I had created #492 which is a simplified version of the `multiple tabs` issue given this issue is related to GTM and the core issue has nothing to do with GTM (as evidenced by your fixes in #573).  I can't recall exactly why I added more tests beyond just [platform\multiple-pages](https://github.com/BuilderIO/partytown/pull/493/files#diff-c9eeeb66bc18faaccbc29d0f141876dbe63a279576051a11a017bf89451f1274) but I'm sure there was a reason.  Possibly we should merge the tests in #493 in to your #573 to provide broader coverage for this issue, especially around integrations?
