### ISSUE TITLE
Uses deprecated APIs - 1 Warning found

### ISSUE THREAD

**Issue by innovatorved** [BuilderIO/partytown#313]
![image](https://user-images.githubusercontent.com/65329423/206392526-1f3b59c9-efaa-44b0-8644-20eeebffe34f.png)

**Comment by harrytran998** [comment]
You should update the title like the warning 😆. Btw, I face with this issue like you.

**Comment by innovatorved** [comment]
Thanks for suggestion @harrytran998

**Comment by majkl-zumberi** [comment]
same issue

**Comment by innovatorved** [comment]
Can you please briefly explain me why this issue occurs @erxclau

**Comment by erxclau** [comment]
> Can you please briefly explain me why this issue occurs @erxclau

@innovatorved From my understanding, before partytown sends Event objects to the web worker, there is a [serialization process](https://github.com/BuilderIO/partytown/blob/main/src/lib/sandbox/main-serialization.ts#L85-L114) that takes place. The function loops through all of the properties of an Event, including the `path` property which happens to be deprecated. There is [currently a check](https://github.com/BuilderIO/partytown/blob/main/src/lib/sandbox/main-serialization.ts#L100-L102) to prevent use of the `path` property but it isn't working because `obj` is not considered an instance of an Event (I'm unsure why). #328 fixes the check.

**Comment by innovatorved** [comment]
Thank you @erxclau
