### ISSUE TITLE
get event if a specific library finished loading

### ISSUE THREAD

**Issue by Omar-ALkhateeb** [BuilderIO/partytown#323]
how can i get event if a specific library finished loading? debug didnt show me any library specific logging

**Comment by adamdbradley** [comment]
Github issues is a place to explain a problem in detail, along with a reproduction case for maintainers. However, Github issues is not the best place to ask how-to questions since project contributors and maintainers don’t have the capacity to debug external websites and the many third-party scripts. 

I think this question is better asked in [Discord](https://discord.gg/hbuEtxdEZ3). Closing for now and hopefully you'll be able to get help there. Additionally, if you're able to find an answer to your question, a PR updating our [docs content](https://github.com/BuilderIO/partytown/tree/main/docs) would be appreciated. Thanks.
