### ISSUE TITLE
How to forward gtag itself (not the data layer)

### ISSUE THREAD

**Issue by rutchkiwi** [BuilderIO/partytown#382]
- [maybe, not good at typescript] I am interested in helping provide a fix!

**Describe the bug**
I can't call gtag wError when forwarding gtag.

In the documentation it is specified that only the datalayer should be forwarded. But I can't see how that would work if I need to call the gtag function elsewhere in my code.

**To Reproduce**
[Repro page here](https://viktorh.net/demo.html)

When clicking the button (which calls gtag()) you get `TypeError: target[$forward$[i]] is undefined`. (You'll need to look in the console)

**Expected behavior**
The event should forward into partytown, and a hit should be sent to GA. In this example I didn't want to use my real GA id but the hit should still be visible in the network panel.

**Partytown version**
0.7.5

**Additional context**
My root issue is I need to call gtag from multiple scripts on some pages. For extra detail, this is necessary when registering conversion on google ads in my case. In the future I would also like to call custom events with gtag from my own javascript.
I have not figured out how to solve this, and I suspect the error I get above is a bug.

Also just want to say that this library concept is amazing. I have really really high hopes that I can make significant speed-ups on my website if I can just get this stuff working! 
Thanks a lot!

**Comment by mikehwagz** [comment]
If you take a look at your gtag snippet, you'll see that the `gtag` function is defined simply as `function gtag(){dataLayer.push(arguments);}`. In other words, it's not doing anything fancy.

**Comment by rutchkiwi** [comment]
Okay I did manage to get this working in the end.

The `TypeError: target[$forward$[i]] is undefined` error
was due to defining a forwarded function like `function gtag = function(){..}`.
I've changed this to `window.gtag = function(){}` and then it worked.

On a larger scale, I did solve this by forwarding gtag itself in this way, instead of just forwarding the datalayer which never worked for reasons I'm not sure about.

**Comment by grantjayy** [comment]
For anyone still looking for a fully integrated solution, I posted it as an answer to this Stack Overflow question:
https://stackoverflow.com/a/76125057/11346564

**Comment by yoyurec** [comment]
> For anyone still looking for a fully integrated solution, I posted it as an answer to this Stack Overflow question: https://stackoverflow.com/a/76125057/11346564

@grantjayy  what is `transport_url: '<TRANSPORT URL FOR SERVER SIDE CONTAINERS>',`?
is somewhere a full working example?
tnx

**Comment by dean-me** [comment]
It took me a long time to get GA4 running on partytown. I finally got it working & I hope to save others some pain :). The issue was that the recommended snippet that Google provides will not work. The recommended snippet looks something like:


<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-XXXXXXXXX');
</script>


To convert this into a working partytown version you need to apply:


<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXX" type="text/partytown"></script>
<script type="text/partytown">
  window.dataLayer = window.dataLayer || [];
  window.gtag = function () {
        dataLayer.push(arguments);
    };
  window.gtag('js', new Date());
  window.gtag('config', 'G-XXXXXXXXX');
</script>

Note:
1.  type="text/partytown" is added to both script tags
2. gtag needs to be a function expression (not declaration) on the window object
3. You need to forward "gtag" & "dataLayer.push" in the partytown definitions as described in the documentation

The gotcha for me was #2 above. I guess the service worker has its own execution context and gtag need to be explicitly defined on window.

**Comment by yoyurec** [comment]
@dean-me  solution works!

question... isn't GA (loaded by GTM) matrics will be totally wrong with using partytown?
i thought service worker will run in parallel, but it runs too late (some kind of "delayed", like other tools can do with 3rd party scripts) and at end of waterfall.
all those 14 seconds of user interactions just lost (((
![image](https://github.com/BuilderIO/partytown/assets/137919/96b263c5-bc39-40b3-8869-b57d86b844d2)
