### ISSUE TITLE
structuredClone getting bad data from ReadPlatform[🐞]

### ISSUE THREAD

**Issue by mrn-rigtved** [BuilderIO/partytown#407]
### Describe the bug

Hey there Im getting this error from `partytown-sandbox-sw.js`
`caught DOMException: Failed to execute 'structuredClone' on 'Window': (...t)=>{const n="function"==typeof t[t.length-1]?t.pop():void 0;return new Promise((r=>{window._klOnsite.push(...<omitted>...)} could not be cloned.
 `
 The data looks fine.

### Reproduction

Localhost

### Steps to reproduce

Im just adding Partytown to the site im working on.

### Browser Info

"Chromium";v="112", "Google Chrome";v="112", "Not:A-Brand";v="99"

**Comment by nick-potts** [comment]
also getting this

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction that we can reproduce on our computers. A failing test in our repo or an easily clonable GitHub repo with minimal reproduction steps is needed.
