### ISSUE TITLE
[🐞] Google Publisher Tag not working with Partytown 

### ISSUE THREAD

**Issue by rossignolli** [BuilderIO/partytown#411]
### Describe the bug

I'm trying to use Google Publisher Tags (GPT) with Partytown, but I'm facing some problems. I was hoping to use Partytown to shift this heavier script execution to a web worker. However, it seems that GPT isn't functioning as expected in this context.

### Reproduction

https://github.com/rossignolli/astro-gpt-test

### Steps to reproduce

1. Create a clean Astro Project
2. Follow [this Google Publiser Tag ad-test show](https://developers.google.com/publisher-tag/guides/get-started)
3. Set up Partytown on a webpage according to the documentation.
4. Initialize Google Publisher Tags on the same page.
5. Attempt to execute GPT scripts within the web worker created by Partytown using [Reverse Proxing](https://partytown.builder.io/proxying-requests#reverse-proxy) shown in the docs.

### Browser Info

Any Browser

### Additional Information

I have observed that when using the <script> tag to load the GPT scripts outside of the Partytown context, everything functions as expected. The issue only arises when attempting to execute the same scripts within the web worker environment provided by Partytown.

The GPT scripts in question require a reverse proxy to function. I have made sure to configure this correctly. Despite this, the scripts still do not execute properly when used with Partytown.

To further illustrate, i used the tutorials indicated in the [Proxying Requests](https://partytown.builder.io/proxying-requests#reverse-proxy) docs.

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction that we can reproduce on our computers. A failing test in our repo or an easily clonable GitHub repo with minimal reproduction steps is needed.
