### ISSUE TITLE
[🐞] Error when GA snippet is blocked by ad blocker

### ISSUE THREAD

**Issue by thdoan** [BuilderIO/partytown#422]
### Describe the bug

There seems to be a conflict between Partytown and ad blockers (I'm using uBlock Origin extension). When you go to a site that is using Partytown with a GA snippet that is blocked, you'll see something like this in the console:

![image](https://github.com/BuilderIO/partytown/assets/4110567/241b2984-aadd-4069-8434-650e1839e34f)

### Reproduction

https://partytown.builder.io/

### Steps to reproduce

You can reproduce it on the Partytown homepage...

1. Install an ad blocker such as uBlock Origin for Chrome
2. Go to https://partytown.builder.io/
3. Open console to see the error

When you disable the ad blocker and the GA snippet is able to load, the error goes away.

### Browser Info

Chrome 114

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction that we can reproduce on our computers. A failing test in our repo or an easily clonable GitHub repo with minimal reproduction steps is needed.

**Comment by thdoan** [comment]
@mhevery please advise on how to submit a "small isolated reproducible issue" if there is no code involved? You can see the issue by going to https://partytown.builder.io/ with an ad blocker enabled (e.g., uBlock Origin).
