### ISSUE TITLE
[🐞]Unable to view GTM in debug mode and not getting Structured markup data coming from GTM

### ISSUE THREAD

**Issue by guptritik146** [BuilderIO/partytown#426]
### Describe the bug

Hi, I tried deploying partytown with our laravel website. I added Google analytics code inline and added datalayer.push in forwards. I managed to remove the CORS error by adding GA inline but now after deploying partytown in production, I am unable to view GTM events in debug mode. Neither am I able to view which events are getting fired and the structured markup has also disappeared from the pages. Please help 🥲

### Reproduction

https://staging.vyaparapp.in/city/chandigarh/free-billing-software

### Steps to reproduce

Here is my Partytown config:
<script> partytown = { forward: ['dataLayer.push', 'gtag'], }; </script>
My GTM Script:
 <script type="text/partytown">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-XXXXX'); </script>
Here is my google analytics script:

        <script type="text/partytown">
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','http://lexample.com/js/google-analytics.js','ga');

            ga('create', 'UA-XXXXX-1', 'auto');
            ga('send', 'pageview');
        </script>
        

### Browser Info

Chrome

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction that we can reproduce on our computers. A failing tests in our repo or an easily clonable GitHub repo with minimal reproduction steps is needed.
