### ISSUE TITLE
[🐞] Partytown x SpeechSynthesis breaks back/forward cache, lowers Lighthouse score

### ISSUE THREAD

**Issue by frederichoule** [BuilderIO/partytown#427]
### Describe the bug

Adding partytown seems to trigger "SpeechSynthesis" on, maybe on an iframe or the worker, which in turn break back/forward cache, which in turn lower Lighthouse score.

### Reproduction

https://partytown.builder.io/

### Steps to reproduce

Chrome DevTools => Application => Back/forward cache => Test

### Browser Info

Chrome

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction.

**Comment by frederichoule** [comment]
It happened on every website that used Partytown, in Google Chrome, but now not anymore. If it happens again I'll reopen. It was probably Chrome's fault.
