### ISSUE TITLE
[🐞] Firefox: 404 error on "/partytown/partytown-sandbox-sw.html?XXXXXX"

### ISSUE THREAD

**Issue by Nicknbt** [BuilderIO/partytown#441]
### Describe the bug

When I go to my website in the Firefox browser and go to hard refresh the page (Cmd + shift + R) I receive a 404 message, causing our tracking scripts to not work.

However, if I were to refresh the page normally (cmd + R) then the web worker works as intended. The issue seems to happening on the Partytown's documentation site as well. 

<img width="1512" alt="Screen Shot 2023-07-18 at 4 38 08 PM" src="https://github.com/BuilderIO/partytown/assets/44065507/9947ff4b-45a8-4fe6-b85e-2d389167de8a">

### Reproduction

https://partytown.builder.io/

### Steps to reproduce

1. Open the URL in Firefox.
2. Open Developer tools on the page.
3. Hard refresh page (Cmd + Shift + R).
4. Notice 404 in the network and console tab.

### Browser Info

Firefox

### Additional Information

Firefox 115.0.2 - MacOS

**Comment by Gitsko** [comment]
I have exactly the same problem with Firefox. :(

**Comment by mhevery** [comment]
The above steps don't reproduce for me.

I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. To us, this means existing failing tests or a minimal reproduction in GitHub which we can clone and easy steps to reproduce.  We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction.

**Comment by aaa123eee** [comment]
I am able to reproduce it 100% of the time on my both win & macos
