### ISSUE TITLE
[🐞] resolveUrl call multiple times if the script tag inserted by webworker

### ISSUE THREAD

**Issue by bdezso** [BuilderIO/partytown#443]
### Describe the bug

1. insert a script tag from the webworker.
2. patchHTMLScriptElement will resolve the url on insertion.
3. initNextScriptsInWebWorker resolve again on script loading

### Reproduction

-

### Steps to reproduce

Try to load gtm.js with resolveUrl

### Browser Info

Chrome

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. To us, this means existing failing tests or a minimal reproduction in GitHub which we can clone and easy steps to reproduce.  We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction.
