### ISSUE TITLE
[🐞]Gatsby 404 for /~partytown/partytown-sandbox-sw.html

### ISSUE THREAD

**Issue by nCuXaP** [BuilderIO/partytown#444]
### Describe the bug

We are using Partytown on a Gatsbyjs 4 project and we constantly get in our analytics 404 errors for this url /~partytown/partytown-sandbox-sw.html
We have followed all the instructions, made the copy lib command and everything is working properly - scripts and events are being loaded and triggered.
We just get from Google search console and other analytics platforms constant reports for large amounts of 404 requests to this address.

Can someone provide guidance as this is impacting both performance and SEO. The website is https://pwd.com.au/.

I am available for providing any additional information.

### Reproduction

https://pwd.com.au/

### Steps to reproduce

You can check the console on the url address provided.

### Browser Info

All browsers

**Comment by mhevery** [comment]
I am sorry, but we need a small isolated reproducible issue; otherwise, we can't spend hours digging into creating a reproduction. We are very sorry, but we can't look at the issue without an isolated reproduction, and we will be closing it. We encourage you to re-open the issue once you have an isolated reproduction.
