### ISSUE TITLE
Syntax errors when executing some scripts from `doubleclick`.

### ISSUE THREAD

**Issue by orballo** [BuilderIO/partytown#51]
I receive the following error every time a script from `https://googleads.g.doubleclick.net/pagead/viewthroughconversion/${SOME_NUMBER_ID}/` is executed by Partytown:

![Screenshot 2022-01-20 at 18 03 37](https://user-images.githubusercontent.com/13615057/150388231-29a7427f-8dea-49ba-8237-a83012528a03.png)

I don't know how to further debug, or if this info is somehow useful for you, but I thought it was worth it at least reporting it.

Let me know if I there is something else I could provide that would be helpful.

**Comment by adamdbradley** [comment]
Would you able to provide a minimal example of how to replicate this? Thanks

**Comment by mareolan** [comment]
I have come across probably the same error with different fetched script. The code in partytown-ww-sw.js creates new Function in which it wraps fetched scripts:
```
with(this){...fetchedScript... ;function thi$(t){return t===this}...}
                              ^ needs \n here
```
which causes problem if the fetched script contains comment on last line (such as // #sourceMappingURL=...) - in such case the new Function content is:
```
with(this){...fetchedScriptLine1
...fetchedScriptLine2
...
// #sourceMappingURL=...;function thi$(t){return t===this}...}
```
i.e. the remaining stuff of the wrapper is added into the comment.

I don't have public example for simulation right now, but when I added \n as shown in 1st example then the error got fixed.

**Comment by sandeshpe** [comment]
I tried integrating GTM with partytown but seems like similar issues. My doubleclick script is failing. Apparently it is not able to parse the content of the script downloaded from doubleclick. 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/90243898/161424164-37b9d28b-6ee8-46d1-9545-20c3004ed866.png">

**Comment by steve8708** [comment]
hey @orballo  - we've just created an issue template, could you update your issue here to provide all the information the template asks for? it'll help us look into your issue https://github.com/BuilderIO/partytown/issues/new?assignees=&labels=&template=bug_report.md&title=

pasting below to make things easier:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Reproduction link**
Please include a link to a Stackblitz or Codesandbox reproducing the issue. We will need to see the issue reproduced with hand-written code - we can't debug giant minified third party scripts directly. If you do not include a clean and simple reproduction of your issue, we won't be able to look into it until you do.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Partytown version**
What version of Partytown you are using, e.g. `0.0.1`

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by adamdbradley** [comment]
Thank you for opening the issue. To help us debug this further, would you be able to provide a way to replicate this? Creating a PR, with the minimal amount of code to re-create the issue would help us debug. A good example to emulate is the Google Tag Manager test: https://github.com/BuilderIO/partytown/tree/main/tests/integrations/gtm

Some more information can be found here: https://github.com/BuilderIO/partytown/blob/main/DEVELOPER.md#submitting-issues-and-writing-tests

Thank you for your help!
