### ISSUE TITLE
Proxytown request stuck on pending

### ISSUE THREAD

**Issue by cwmrowe** [BuilderIO/partytown#91]
I am attempting to integrate TrustArc, a third party cookie consent manager, with PartyTown. However it isn't showing the consent dialog as expected in an incognito window.

I notice that the the last request to "proxytown" in the network tab is stuck on pending.

![Screenshot 2022-02-28 at 11 05 52](https://user-images.githubusercontent.com/407167/155972917-f6435a97-fb99-4727-badb-1fafccc86e97.png)

The request payload is:
```javascript
{
  "$msgId$": 939543253,
  "$tasks$": [
    {
      "$winId$": 728533565,
      "$instanceId$": 1,
      "$applyPath$": [
        "addEventListener",
        [
          1,
          [
            [
              0,
              "readystatechange"
            ],
            [
              4,
              {
                "$winId$": 728533565,
                "$instanceId$": 1,
                "$refId$": 392264080
              }
            ],
            [
              0,
              false
            ]
          ]
        ]
      ],
      "$debug$": "document.addEventListener.1,0,readystatechange,4,[object Object],0,false (non-blocking)"
    },
    {
      "$winId$": 728533565,
      "$instanceId$": 0,
      "$applyPath$": [
        "addEventListener",
        [
          1,
          [
            [
              0,
              "message"
            ],
            [
              4,
              {
                "$winId$": 728533565,
                "$instanceId$": 0,
                "$refId$": 563258573
              }
            ],
            [
              0,
              false
            ]
          ]
        ]
      ],
      "$debug$": "addEventListener.1,0,message,4,[object Object],0,false (non-blocking)"
    },
    {
      "$winId$": 728533565,
      "$instanceId$": 1,
      "$applyPath$": [
        "getElementsByTagName",
        [
          1,
          [
            [
              0,
              "SCRIPT"
            ]
          ]
        ]
      ],
      "$debug$": "document.getElementsByTagName.1,0,SCRIPT (blocking)"
    }
  ]
}
```

Any help would be greatly appreciated.

**Comment by shailander** [comment]
@cwmrowe Is it failing after the pending status? I guess you have the same issue as #87

**Comment by adamdbradley** [comment]
Which version of Partytown is this?

**Comment by steve8708** [comment]
hey @cwmrowe - we've just created an issue template, could you update your issue here to provide all the information the template asks for? it'll help us look into your issue https://github.com/BuilderIO/partytown/issues/new?assignees=&labels=&template=bug_report.md&title=

pasting below to make things easier:

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Reproduction link**
Please include a link to a Stackblitz or Codesandbox reproducing the issue. We will need to see the issue reproduced with hand-written code - we can't debug giant minified third party scripts directly. If you do not include a clean and simple reproduction of your issue, we won't be able to look into it until you do.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by adamdbradley** [comment]
Closing this issue since it has become stale, or has been addressed in recent releases and docs updates. If you feel this is still an issue please reopen a new issue. Thanks.
